services:
  java_database:
    image: mysql
    container_name: java_database
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: budget_planner_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
  java_phpmyadmin:
    image: phpmyadmin
    container_name: java_phpmyadmin
    environment:
      PMA_HOST: java_database
      PMA_PORT: 3306
    ports:
      - "6500:80"
    depends_on:
      - java_database
  java_backend:
    image: atakowiec/java-finance-manager:backend
    container_name: java_backend
    ports:
      - "5000:5000"
    depends_on:
      - java_database
    environment:
      DATABASE_HOST: java_database
      DATABASE_PORT: 3306
      DATABASE_NAME: budget_planner_db
      DATABASE_USER: user
      DATABASE_PASSWORD: pass
      MAIL_HOST: smtp.gmail.com
      MAIL_PORT: 587
      MAIL_USERNAME: username
      MAIL_PASSWORD: password